@echo off
echo [*] Starting tcpvcon capture to log...
start /B "" "C:\Users\Griffith\Desktop\hfz_work\tools\tcpview\tcpvcon64.exe" -a -c > "C:\Users\Griffith\Desktop\hfz_work\analysis\capture_log.csv" 2>&1
echo [*] tcpvcon started. PID of tcpvcon is unknown.
echo [*] Launching HFZ...
start "" /B "C:\Users\Griffith\Desktop\hfz_work\HFZ Activator A12+ Premium V1.2\HFZ Activator A12+ Premium.exe"
echo [*] Waiting 60 seconds...
ping -n 60 127.0.0.1 >nul
echo [*] Killing tcpvcon...
taskkill /IM tcpvcon64.exe /F >nul 2>&1
echo [*] Done! Check analysis\capture_log.csv
pause
